/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.FileManager;
import BUS.LichThiManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author Rexviet
 */
public class FormMain extends javax.swing.JFrame {
    private Vector colName = new Vector ();
    private String currentDir;
    private File[] allFiles;
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        File f = new File (".");
        try {
            currentDir = f.getCanonicalPath();
            System.out.println(currentDir);
            allFiles = f.listFiles(XlsxFileFilter.getInstance());
            
        } catch (IOException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        colName.addElement("Mã MH");
        colName.addElement("Tên MH");
        colName.addElement("SBD");
        colName.addElement("Phòng");
        colName.addElement("Ngày thi");
        colName.addElement("Ca thi");
    }
    
    private void setDataToTable (Vector Data) {
        tbLichThi.setModel(new DefaultTableModel (Data, colName));
        this.setColumnSize();
    }
    
    private void setColumnSize () {
        TableColumnModel colModel = tbLichThi.getColumnModel();
        colModel.getColumn(1).setPreferredWidth(250);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        btnNen = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLichThi = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        mSearch = new javax.swing.JMenuItem();
        mExport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mExit = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        mTut = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Vizion] Tool Xem Lịch Thi v2.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nhập MSSV:");

        txtMSSV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMSSVKeyPressed(evt);
            }
        });

        btnNen.setText("Nện");
        btnNen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNenActionPerformed(evt);
            }
        });

        btnExport.setText("Xuất file Excel");
        btnExport.setEnabled(false);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNen)
                    .addComponent(btnExport)
                    .addComponent(btnExit))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tbLichThi.setModel(new DefaultTableModel (new Vector(), colName));
        tbLichThi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(tbLichThi);

        Menu1.setText("Chức Năng");

        mSearch.setText("Tìm Lịch Thi");
        mSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSearchActionPerformed(evt);
            }
        });
        Menu1.add(mSearch);

        mExport.setText("Xuất File Excel");
        mExport.setEnabled(false);
        mExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExportActionPerformed(evt);
            }
        });
        Menu1.add(mExport);
        Menu1.add(jSeparator1);

        mExit.setText("Thoát");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        Menu1.add(mExit);

        jMenuBar1.add(Menu1);

        menu2.setText("Giúp Đỡ");

        mTut.setText("Cách Sử Dụng");
        mTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTutActionPerformed(evt);
            }
        });
        menu2.add(mTut);

        mAbout.setText("Giới Thiệu");
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });
        menu2.add(mAbout);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setDataToTable(new Vector ());
    }//GEN-LAST:event_formWindowOpened
    
    private void Search () {
        String MSSV = txtMSSV.getText();
        if (MSSV.isEmpty())
            JOptionPane.showMessageDialog(this, "Mã số sinh viên không được để trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            // clear old data
            LichThiManager.getInstance().Clear();
            
            // load new data
            try {
                for (File f : allFiles)
                    FileManager.getInstance().DocDanhSachPhongThi(f, MSSV);
            } catch (IOException | InvalidFormatException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // set new data to table
            this.setDataToTable(LichThiManager.getInstance().getDataVector());
            JOptionPane.showMessageDialog(this, "Tìm lịch thi hoàn tất.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // enable export function
            btnExport.setEnabled(true);
            mExport.setEnabled(true);
        }
    }
    
    private void Export () { 
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("XLSX file", "xlsx"));
        fc.setAcceptAllFileFilterUsed(false);
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File saveFile = fc.getSelectedFile();
            System.out.println(saveFile.getPath());
            try {
                FileManager.getInstance().exportToXLSXFile(saveFile.getPath() + ".xlsx");
                JOptionPane.showMessageDialog(this, "Xuất file hoàn tất!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "Có lỗi khi xuất file", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void OpenWeb (String url) {
    // open homepage, base on current OS
        String os = System.getProperty("os.name").toLowerCase();
        try {
            Runtime rt = Runtime.getRuntime();
            if (os.contains("win"))
                rt.exec( "rundll32 url.dll,FileProtocolHandler " + url);
            else if (os.contains("mac"))
                rt.exec( "open " + url);
            else if (os.contains("nix") || os.contains("nux")) {
                String[] browsers = {"epiphany", "firefox", "mozilla", "konqueror",
                                     "netscape","opera","links","lynx"};

                StringBuilder cmd = new StringBuilder();
                for (int i=0; i<browsers.length; i++)
                     cmd.append(i==0  ? "" : " || ").append(browsers[i]).append(" \"").append(url).append("\" ");

                rt.exec(new String[] { "sh", "-c", cmd.toString() });
            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Có lỗi khi mở trình duyệt", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void Exit () {
        System.exit(0);
    }
    
    private void btnNenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNenActionPerformed
        Search ();
    }//GEN-LAST:event_btnNenActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        Export ();
    }//GEN-LAST:event_btnExportActionPerformed
    
    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed
        OpenWeb ("http://vizionteam.com/");
    }//GEN-LAST:event_mAboutActionPerformed

    private void mSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSearchActionPerformed
        Search ();
    }//GEN-LAST:event_mSearchActionPerformed

    private void mExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExportActionPerformed
        Export ();
    }//GEN-LAST:event_mExportActionPerformed

    private void mTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTutActionPerformed
        OpenWeb ("http://vizionteam.com/xem_lich_thi/help.html");
    }//GEN-LAST:event_mTutActionPerformed

    private void txtMSSVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMSSVKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER)
           Search ();
    }//GEN-LAST:event_txtMSSVKeyPressed
    
    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        Exit ();
    }//GEN-LAST:event_mExitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Exit ();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnNen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mExport;
    private javax.swing.JMenuItem mSearch;
    private javax.swing.JMenuItem mTut;
    private javax.swing.JMenu menu2;
    private javax.swing.JTable tbLichThi;
    private javax.swing.JTextField txtMSSV;
    // End of variables declaration//GEN-END:variables
}
